### PR TITLE
Typescript git action

### LINKED ISSUE #106: Typescript Type Checking for Git Action
Git Action Continuous Integration should check whether typescript compiles successfully or not.

if there is any compilation error, the PR should not be merged.

### LINKED ISSUE #114: Remove PrivateRoute Component and Introduce AppRoute
# Motivation
- PrivateRoute only check authorities in JWT token. which is incorrect.
- PrivateRoute is generated by jhipster, not suitable to our context anymore
- Internally, AppRoute uses AuthorizationChecker #77

### PR DESCRIPTION
**Pull request by kachun333**
please merge #105 first

1. refractor PrivateRoute and introduce AppRoute. resolved #114
2. add bug report issue template abcaf6842981daf265358ec2e0611e5181f0517f
3. add typescript type checking during Git Action CI. resolved #106

### CODE REVIEW

File: src/main/webapp/app/shared/util/tab.constants.ts [hunk 1]
```diff
@@ -1,70 +1,94 @@
 import { ITabInfo } from 'app/shared/components/customTab/custom-tab';
+import CCRole from '../model/enum/cc-role.enum';
+import EventRole from '../model/enum/event-role.enum';
 
 export const eventMainTabList: ITabInfo[] = [
   {
     tabName: 'Upcoming',
     tabTranslateKey: 'clubmanagementApp.event.upcoming',
-    tabRoute: '/entity/event'
+    tabRoute: '/event/event',
```
Comment (junzai97) [inline src/main/webapp/app/shared/util/tab.constants.ts]: Should be `entity/event`

File: src/main/webapp/app/modules/auth/complete-profile/complete-profile.reducer.ts [hunk 2]
```diff
@@ -65,36 +65,36 @@ export default (state: CompleteProfileState = initialState, action): CompletePro
         updateSuccess: true,
         loading: false,
         errorMessage: null,
-        userProfile: action.payload.data
+        userProfile: action?.payload?.data ?? defaultValue,
```
Comment (junzai97) [inline src/main/webapp/app/modules/auth/complete-profile/complete-profile.reducer.ts:68]: I'm facing compiled error for this line of code and lin 75, when starting the Front End. But the error is gone after I removed the `?? defaultValue`. Do you have any idea what caused the error?

``` 
 ERROR  Failed to compile with 1 errors
 error  in ./src/main/webapp/app/modules/auth/complete-profile/complet

Module parse failed: Unexpected token (39:142)
You may need an appropriate loader to handle this file type.
|             return Object.assign({}, state, { updating: false, updat
|         case SUCCESS(ACTION_TYPES.COMPLETE_USERPROFILE):
>             return Object.assign({}, state, { updating: false, updatad ? .data ?  ? defaultValue :  :  :  :  });
|         case SUCCESS(ACTION_TYPES.FETCH_USERPROFILE_UNIINFO):
|             return Object.assign({}, state, { loading: false, errorM
:  });

 @ ./src/main/webapp/app/shared/reducers/index.ts 37:0-89 60:4-19
 @ ./src/main/webapp/app/config/store.ts
 @ ./src/main/webapp/app/index.tsx
 @ multi (webpack)-dev-server/client?http://localhost:9060 (webpack)/h
```

Comment (kachun333) [reply src/main/webapp/app/modules/auth/complete-profile/complete-profile.reducer.ts:68]: please do a `npm install` before running the code.
There are updates on `typescript` and `prettier` package.

I'm quite sure that the code is fine because the GitAction Ci doesn't complaint

Comment (kachun333) [reply src/main/webapp/app/modules/auth/complete-profile/complete-profile.reducer.ts:68]: fixed in 3fc02c7c262735ceef449adfbca62fa9ecadd061

File: src/main/webapp/app/shared/util/tab.constants.ts (hunk 1 above)
Comment (kachun333) [reply src/main/webapp/app/shared/util/tab.constants.ts]: fixed in 3fc02c7c262735ceef449adfbca62fa9ecadd061

**Review by junzai97 — APPROVED** [review]

**Review by HowardYaw — APPROVED** [review]
